apply plugin: 'groovy'

ext {
    jobDslVersion = '1.93'
    jenkinsVersion = '2.479.3'
}

repositories {
    mavenCentral()
    maven {
        url 'https://repo.jenkins-ci.org/public/'
    }
}

sourceSets {
    main {
        groovy {
            // src/ is the root so 'package util' resolves to src/util/
            srcDirs = ['src']
            include 'util/**'
        }
    }
    jobs {
        groovy {
            srcDirs = ['src/jobs']
        }
    }
    test {
        groovy {
            srcDirs = ['test/groovy']
        }
    }
}

configurations {
    testPlugins {}
}

dependencies {
    implementation 'org.codehaus.groovy:groovy:3.0.21'
    implementation "org.jenkins-ci.plugins:job-dsl-core:${jobDslVersion}"

    testImplementation 'org.spockframework:spock-core:2.3-groovy-3.0'
    testImplementation 'org.jenkins-ci.main:jenkins-test-harness:2411.v1e79b_0dc94b_7'
    testImplementation "org.jenkins-ci.main:jenkins-war:${jenkinsVersion}"

    testImplementation "org.jenkins-ci.plugins:job-dsl:${jobDslVersion}"
    testImplementation "org.jenkins-ci.plugins:job-dsl:${jobDslVersion}@jar"
    testImplementation 'org.jenkins-ci.plugins:structs:338.v848422169819@jar'
    testImplementation 'org.jenkins-ci.plugins:script-security:1369.v9b_98a_4e95b_2d@jar'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    inputs.files sourceSets.jobs.groovy.srcDirs
    systemProperty 'buildDirectory', project.buildDir.absolutePath
    useJUnitPlatform()
}